// Edit this file to update the text across both v1 and v2.
window.BD_CONTENT = {
  config: {
    title: "Birthday Story V2",
    passcode: "1306",
    messages: {
      unlocked: "Unlocked",
      wrongPasscode: "Wrong passcode. Try the birthday date",
    },
    galleryNext: "Next",
  },
  text: {
    '.screen[data-screen="welcome"] .eyebrow': "My Kit2",
    '.screen[data-screen="welcome"] .display-title': "A Special day requires a Special Celebration",
    '.screen[data-screen="welcome"] .hero-copy': "",
    '.screen[data-screen="welcome"] [data-next="invite"]': "Let's Begin",
    ".welcome-showcase .mini-badge": "My bubu",
    ".welcome-showcase h2": "A beautiful night of memories, music, and surprises",
    ".welcome-showcase p": "Sit tight and enjoy the night with the person who loves you the most in entire world 😘",
    '.screen[data-screen="invite"] .eyebrow': "My Shoni",
    '.screen[data-screen="invite"] .section-title': "Tumhara Birthday Celebrate karna mere liye kisi FESTIVAL se kam nahi मेरी जान 🫠",
    '.screen[data-screen="invite"] .section-copy': "Do you want to celebrate your birthday with me bubu?",
    "#noButton": "No",
    '.screen[data-screen="invite"] [data-next="unlock"]': "Yes",
    '.screen[data-screen="unlock"] .eyebrow': "MY Jaan",
    ".polaroid-main p": "For her day",
    '.screen[data-screen="unlock"] .section-title': "Enter the Passkey",
    '.screen[data-screen="unlock"] .section-copy': "",
    '.key[data-action="clear"]': "Clear",
    '.key[data-action="delete"]': "Delete",
    ".hint-text": "Hint: Kit2's birthday it is - 😘😘😘",
    '.screen[data-screen="message"] .eyebrow': "My Love",
    '.screen[data-screen="message"] .section-title': "A soft little letter for my KIT2 ❤️",
    ".letter-line-a": "TBD LETTER",
    ".letter-line-b": "",
    '.screen[data-screen="message"] [data-next="gallery"]': "Next",
    '.screen[data-screen="gallery"] .eyebrow': "Memories",
    '.screen[data-screen="gallery"] .section-title': "I know long disatance sucks, But I belive in US",
    '.screen[data-screen="finale"] .eyebrow': "Meri Mithu , Meri Kit22222",
    '.screen[data-screen="finale"] .section-title': "Happy Birthday BUBUUUUUUUUUU 😘😘😘",
    ".finale-note": "",
    "#vaultEntryButton": "Unlock Suprises",
    '.screen[data-screen="vault"] .eyebrow': "Gift Vault",
    '.screen[data-screen="vault"] .section-title': "A few little surprises are waiting for you Bubu",
    '.screen[data-screen="vault"] .section-copy': "",
    ".vault-history-head .mini-badge": "Gifts",
    ".vault-history-head h3": "Unlocked gifts",
    ".vault-history-head p": "",
    "#vaultBeginButton": "Unlock this gift",
    "#vaultNextButton": "Show next gift",
    "#vaultModalTitle": "Do you want to unlock this gift?",
    '#vaultModal [data-vault-stage="intro"] .section-copy': "One small passkey away, and the next surprise will reveal itself",
    '#vaultModal [data-vault-stage="intro"] .mini-badge': "Gift ready",
    "#vaultStartUnlock": "Unlock gift",
    '#vaultModal [data-vault-stage="code"] .mini-badge': "Passkey",
    '#vaultModal [data-vault-stage="code"] .modal-title': "Enter the passkey",
    '#vaultModal [data-vault-stage="code"] .section-copy': "",
    '#vaultModal [data-vault-stage="success"] .mini-badge': "Gift unlocked",
    '#vaultModal [data-vault-stage="success"] .modal-title': "Your surprise is open",
    '#vaultModal [data-vault-stage="success"] .section-copy': "",
    "#vaultModalContinue": "Continue",
    ".wish-message": "Happy Birthday to the softest, brightest part of my world",
    "#secretLetterLabel": "The longer version",
    "#secretLetterModal .modal-body p:first-of-type": "Replace this with the full birthday note later. This spot is ideal for the personal message you do not want to place directly on the screen",
    "#secretLetterModal .modal-body p:last-of-type": "Keep it more intimate here: the things you admire, the memories you want to hold on to, and what you hope this next year gives her",
    "#cryingModalLabel": "No?",
    "#cryingOverlay p": "नहीं  न  शोनी ऐसा  नहीं  करो मेरी  जान",
    "#pleaseButton": "Please",
  },
  vault: {
    waitingBadge: "Waiting",
    waitingTitle: "A wrapped little surprise",
    waitingCopy: "Tap the button below",
    emptyHistory: "Nothing has been unlocked yet",
    completeBadge: "Complete",
    completeTitle: "Every hidden gift is unlocked",
    completeCopy: "The full little gift list is waiting on the right now",
    unlockedBadge: "Gift unlocked",
  },
};
