// Edit this file to update the text across both v1 and v2.
window.BD_CONTENT = {
  config: {
    title: "Birthday Story V2",
    passcode: "1306",
    messages: {
      unlocked: "Unlocked.",
      wrongPasscode: "Wrong passcode. Try the birthday date.",
    },
    galleryNext: "Next",
  },
  text: {
    '.screen[data-screen="welcome"] .eyebrow': "Birthday Story V2",
    '.screen[data-screen="welcome"] .display-title': "A more cinematic version of the surprise.",
    '.screen[data-screen="welcome"] .hero-copy': "This version layers in the strongest upgrades: modal reveals, masked transitions, spotlight glow, placeholders for your own media, and a more premium visual mood.",
    '.screen[data-screen="welcome"] [data-next="invite"]': "Start chapter one",
    ".welcome-showcase .mini-badge": "for bubu",
    ".welcome-showcase h2": "A little night of memories, music, and hidden surprises.",
    ".welcome-showcase p": "One smooth story that starts softly, glows brighter, and ends with secret gifts waiting to be unlocked one by one.",
    '.screen[data-screen="invite"] .eyebrow': "Chapter 2",
    '.screen[data-screen="invite"] .section-title': "I feel gifted to celebrate your birthday.",
    '.screen[data-screen="invite"] .section-copy': "Do you want to celebrate your birthday with me bubu?",
    "#noButton": "No",
    '.screen[data-screen="invite"] [data-next="unlock"]': "Yes",
    '.screen[data-screen="unlock"] .eyebrow': "Chapter 3",
    ".polaroid-main p": "For her day",
    '.screen[data-screen="unlock"] .section-title': "Enter the birthday date",
    '.screen[data-screen="unlock"] .section-copy': "The passcode is the day and month together. Once it matches, the next screen blooms in with a clean transition.",
    '.key[data-action="clear"]': "Clear",
    '.key[data-action="delete"]': "Delete",
    ".hint-text": "Hint: Kit2's birthday it is - 😘😘😘",
    '.screen[data-screen="message"] .eyebrow': "Chapter 4",
    '.screen[data-screen="message"] .section-title': "A soft little letter for her",
    ".letter-line-a": "This chapter introduces the story more gently, with staged text reveal and a button that opens a full Bootstrap modal for the hidden version of the note.",
    ".letter-line-b": "Keep the on-page text short, then use the modal for something more intimate and personal when you customize it.",
    '[data-bs-target="#secretLetterModal"]': "Open full letter",
    '.screen[data-screen="message"] [data-next="gallery"]': "Go to memories",
    '.screen[data-screen="gallery"] .eyebrow': "Chapter 5",
    '.screen[data-screen="gallery"] .section-title': "Memory moments",
    '.screen[data-screen="finale"] .eyebrow': "Final chapter",
    '.screen[data-screen="finale"] .section-title': "One last surprise",
    ".finale-note": "A tiny ending scene for the birthday girl. Tap the cake for a little celebration, then open the next page to unlock what is waiting.",
    "#vaultEntryButton": "Unlock Gift",
    '.screen[data-screen="vault"] .eyebrow': "Secret vault",
    '.screen[data-screen="vault"] .section-title': "A few little gifts are waiting for you.",
    '.screen[data-screen="vault"] .section-copy': "Each surprise unlocks one at a time. Every passkey reveals a new gift and adds it quietly to your history.",
    ".vault-history-head .mini-badge": "Order history",
    ".vault-history-head h3": "Unlocked gifts",
    ".vault-history-head p": "Every revealed surprise gets saved here with its image and tiny note.",
    "#vaultBeginButton": "Unlock this gift",
    "#vaultNextButton": "Show next gift",
    "#vaultModalTitle": "Do you want to unlock this gift?",
    '#vaultModal [data-vault-stage="intro"] .section-copy': "One small passkey away, and the next surprise will reveal itself.",
    '#vaultModal [data-vault-stage="intro"] .mini-badge': "Gift ready",
    "#vaultStartUnlock": "Unlock gift",
    '#vaultModal [data-vault-stage="code"] .mini-badge': "Passkey",
    '#vaultModal [data-vault-stage="code"] .modal-title': "Enter the passkey",
    '#vaultModal [data-vault-stage="code"] .section-copy': "The same soft little code opens each hidden surprise.",
    '#vaultModal [data-vault-stage="success"] .mini-badge': "Gift unlocked",
    '#vaultModal [data-vault-stage="success"] .modal-title': "Your surprise is open.",
    '#vaultModal [data-vault-stage="success"] .section-copy': "It has been added to your history, and the next one is quietly waiting.",
    "#vaultModalContinue": "Continue",
    ".wish-message": "Happy Birthday to the softest, brightest part of my world.",
    "#secretLetterLabel": "The longer version",
    "#secretLetterModal .modal-body p:first-of-type": "Replace this with the full birthday note later. This spot is ideal for the personal message you do not want to place directly on the screen.",
    "#secretLetterModal .modal-body p:last-of-type": "Keep it more intimate here: the things you admire, the memories you want to hold on to, and what you hope this next year gives her.",
    "#cryingModalLabel": "No?",
    "#cryingOverlay p": "nahi n Shoni aaisa nahi karo jaan",
    "#pleaseButton": "Please",
  },
  vault: {
    waitingBadge: "Waiting",
    waitingTitle: "A wrapped little surprise",
    waitingCopy: "Each unlocked gift appears here first, then slides into your history on the right so the whole story keeps building.",
    emptyHistory: "Nothing has been unlocked yet.",
    completeBadge: "Complete",
    completeTitle: "Every hidden gift is unlocked.",
    completeCopy: "The full little order history is waiting on the right now.",
    unlockedBadge: "Gift unlocked",
  },
};
